platform :ios, '8.0'

pod 'CSStickyHeaderFlowLayout'
pod 'UIImage-Helpers'
pod 'FontAwesomeKit/FontAwesome'
pod 'EDColor'
pod 'AFNetworking'
pod 'XHRealTimeBlur'
pod 'ZFDragableModalTransition', :git => 'git@github.com:MikeSilvis/ZFDragableModalTransition.git', :branch => 'adding-top-and-mutliple-transitions'
pod 'SVWebViewController', :git => 'https://github.com/MikeSilvis/SVWebViewController.git'
pod 'Underscore.m'
