platform :ios, '8.0'

pod 'CSStickyHeaderFlowLayout'
pod 'FontAwesomeKit/FontAwesome'
pod 'EDColor'
pod 'AFNetworking'
pod 'XHRealTimeBlur'
pod 'ZFDragableModalTransition', :git => 'git@github.com:MikeSilvis/ZFDragableModalTransition.git', :branch => 'adding-top-and-mutliple-transitions'
pod 'Underscore.m'
pod 'SDWebImage'
pod 'MPGNotification', :git => 'git@github.com:MikeSilvis/MPGNotification.git'
pod 'Mixpanel'
